### ISSUE TITLE
Duda ClasificadoresBase Resultado (con los datos BCW y ADULT)

### ISSUE THREAD

**Issue by Dguipla** [Dguipla/TFM-SemiSup#28]
Duda respecto a los resultados conseguidos hasta ahora con los datos BCW y ADULT con los clasificadores Base (supervisado)

Para discutirlo a la vuelta de vacaciones:

Resultados (accuracy) : (https://github.com/Dguipla/TFM-SemiSup/blob/main/notebooks/ClasificadoresSupervisado/resultsClasificadoresBase.csv)

PD: añadiré el resultado de los otros conjunto de datos en cuanto tenga hecho el pipeline de featurization de cada uno para acloplarlo con el pipeline general

**Comment by alvarag** [comment]
Es un poco extraño que siga una tendencia de mejoría en los conjuntos de datos a medida que etiquetamos más datos...

Para ver bien estas tendencias podría ser interesante hacer unas gráficas (una por cada conjunto de datos). Cada línea será el resutlado de un clasificador y será de un color para que puedan representarse distintos clasificadores en la misma gráfica. Mi idea es poner en el eje _y_ la precisión (accuracy) y en el eje _x_ el porcentaje de etiquetado.

**Comment by Dguipla** [comment]
Os adjunto un dashboard en powerBi con todo los resultados para los clasificadores base @alvarag de momento no he implementado SemiSupervisado (no estaria etiquetando) como la idea es comparar Supervisado vs SemiSupervisado he comenzado con los supervisados donde la idea es analizar el accuraccy sacando datos es decir comienzo con 1% para los datos de trainning entreno, genero el modelo y despues utilizo los datos de test para extraer el resultado , despues los mismo con un 5% así succesivamente para todos los conjuntos de datos e clasificadores base (supervisado).


[https://github.com/Dguipla/TFM-SemiSup/tree/main/notebooks/ClasificadoresSupervisado/Resultados](url)

También adjunto el pdf del dashboard: 

[https://app.zenhub.com/files/323652909/b10c858f-e804-4814-b998-6ebbcc7ec718/download](https://app.zenhub.com/files/323652909/b10c858f-e804-4814-b998-6ebbcc7ec718/download)

Gracias, 

David.

**Comment by Dguipla** [comment]
He añadido un resumen de los resultados para los clasificadores base (modificando el tamaño de datos de entrenamiento para posteriormente compararlo con SemiSupervisado) creo que se entiende mejor: 


[https://github.com/Dguipla/TFM-SemiSup/blob/main/notebooks/ClasificadoresSupervisado/Resultados/results.ipynb](url)

Métricas y resultados: 
[https://github.com/Dguipla/TFM-SemiSup/blob/main/notebooks/ClasificadoresSupervisado/Resultados/resultsClasificadoresBase.csv](url)

Por otro lado creo que tiene mas sentido en vez de utilizar % de datos etiquetados trabajar por orden de magnitud (<100, <1000, <10000....) ya que para nuestro caso tenemos un tamaño diferente para cada conjunto y no es lo mismo 1% de 500 casos (BCW) que 1% para 1M casos (POKER).

**Comment by Dguipla** [comment]
He añadido un notebook en python con los resultados (para los clasificadores base con diferentes tamaños de los datos de entrenamiento para posteriormente compararlo con los modelos SemiSupervisados) añadiendo otras metricas, creo que ahora se puede entender mejor :

[https://github.com/Dguipla/TFM-SemiSup/blob/main/notebooks/ClasificadoresSupervisado/Resultados/results.ipynb](url)

Medidas y métricas:
[https://github.com/Dguipla/TFM-SemiSup/blob/main/notebooks/ClasificadoresSupervisado/Resultados/resultsClasificadoresBase.csv](url)

Al tener diferentes tamaños en los conjuntos de datos  creo que tendria más sentido trabajar por orden de magnitud para los datos etiquetados (<100, <1000, <10000...) que %, ya que  no es lo mismo el 1% del conjunto de BCW con 500 instancias que el 1% del conjunto POKER con 1M de instancias. 

Por otro lado, implementando el SefTrainning, para los casos de muy pocos datos etiquetados la probabilidad que me da los clasificadores base ya en la primera iteración es muy alta es decir casi siempre da valores de probabilidad >0.98 (por la simplicidad del modelo entiendo) excepto para RF. Con lo que en la primera iteración añadiría prácticamente  todos los datos  NoEtiquetados como validos juntamente con sus predicciones.

**Comment by alvarag** [comment]
Lo vemos en la próxima reunión que hay cosas interesantes que has planteado y mucho trabajo hecho. ¿Tenemos fecha para la próxima reunión @Dguipla ?

**Comment by Dguipla** [comment]
Perfecto, no tenemos aún fecha para la próxima reunión, por mi lado me iría bien de 12-13 o de 17:30-18:30 (cualquier día).  Cuando os vaya mejor  me comentais y organizo la reunión (@alvarag @jjrodriguez)

Por otro lado estoy acabando la clase con sus métodos para SelfTraining, la idea es hacerla servir como las otras clases de casificadores, DecisionTreeClassifier, RandomForest… pero con la diferencia que se necesita un parámetro de entrada, un clasificadorBase.  La idea es posteriormente crear un dataFrame con todos los resultados para poder analizarlos, similar a esta estructura (tambien lo podemos comentar): 

![image.png](https://images.zenhubusercontent.com/5fe226a8e76f3fd56f6eec06/87565092-d2fc-4a5e-9ef7-0597d83eef89)

Muchas gracias!
