### ISSUE TITLE
Scatter - Duda (Keel vs Spark)

### ISSUE THREAD

**Issue by Dguipla** [Dguipla/TFM-SemiSup#44]
Sobre la figura para comparar keel y Spark, aqui tengo un ejemplo de como quedaria lo que no se si esta correcto del todo ¿? No me queda claro ...
![image.png](https://images.zenhubusercontent.com/5fe226a8e76f3fd56f6eec06/d700a033-bc4d-4a2a-85bc-f1341547da57)

**Comment by alvarag** [comment]
No del todo, la idea es que cada punto represente dos ejecuciones (una en Spark y una en Keel). Imagina que tenemos el siguiente resultado para un dataset concreto:

- Spark: 0.65
- Keel: 0.61

Representarías un único punto en la coordenada (0.65, 0.61) que representa el dataset en ese espacio de dos dimensiones de la precisión en Keel vs Spark.

De este modo, vas a tener tantos puntos como datasets y todos de un mismo color, pues cada punto representa la ejecución en Keel y en Spark.

**Comment by Dguipla** [comment]
Creo que ahora sí que seria correcto, ahora me cuadra más: 

![image.png](https://images.zenhubusercontent.com/5fe226a8e76f3fd56f6eec06/496deb1d-f076-467f-af47-bb2ddcbfd603)
![image.png](https://images.zenhubusercontent.com/5fe226a8e76f3fd56f6eec06/f8239483-4ae4-4484-a70d-bcb3d0969328)

**Comment by alvarag** [comment]
Esa sería la idea, lo único poner los puntos más pequeños para que no se monten unos con otros y tal vez cada punto de un color (y que se mantenga en todos los gráficos), de esta manera cada color representa un dataset
