### ISSUE TITLE
Crear una biblioteca de Spark

### ISSUE THREAD

**Issue by alvarag** [Dguipla/TFM-SemiSup#47]
Las instrucciones para crear una biblioteca de Spark con el código que tienes en los notebooks sería algo como lo que puedes ver en [este repositorio](https://github.com/mjuez/sbt_scala_spark_hello_world), cortesía de [Mario Juez](https://github.com/mjuez) (predoctoral del área).

Para poder crear el paquete, vas a necesitar [instalarte sbt](https://www.scala-sbt.org/1.x/docs/Setup.html) en tu máquina.

Luego los pasos serían:

- Crear un directorio src, dentro uno main... así hasta tener algo del estilo a ```src/main/scala/org/apache/spark/ml/semisupervised```
-  Sacar el código de las clases a ficheros independientes y dejarlos en al ruta anterior. Por ejemplo: ```src/main/scala/org/apache/spark/ml/semisupervised/SelfLearning.scala```
- Crear un fichero [build.sbt](https://github.com/mjuez/sbt_scala_spark_hello_world/blob/main/build.sbt), donde cambiarás el nombre (como se llamará el paquete), la organización (en tu caso ubu, por ejemplo), el resto son versiones que no deberías necesitar cambiar.
- Crear una carpeta [```project```](https://github.com/mjuez/sbt_scala_spark_hello_world/tree/main/project)
- En dicha carpeta crear dos ficheros:
  - [build.properties](https://github.com/mjuez/sbt_scala_spark_hello_world/blob/main/project/build.properties) En su interior pones la versión de sbt que hayas instalado en tu equipo.
  - [plugins.sbt](https://github.com/mjuez/sbt_scala_spark_hello_world/blob/main/project/plugins.sbt) No hace falta que cambies nada, copias el que hay en el repositorio indicado arriba.

Una vez tengas todo en su sitio, debería ser tan sencillo como ejecutar en tu consola ``` sbt package ```, creará un directorio target/scala... donde aparecerá el "xxx.jar" con tu biblioteca.

Ejemplo:
```sh
➜  sbt_scala_spark_hello_world git:(main) git clone https://github.com/mjuez/sbt_scala_spark_hello_world.git
...
➜  sbt_scala_spark_hello_world git:(main) sbt package
...
[info]   Compilation completed in 19.006s.
[success] Total time: 42 s, completed 09-mar-2021 15:49:54
➜  sbt_scala_spark_hello_world git:(main) ls target/scala-2.12/
classes  spark_hw_2.12-1.0.0.jar  update  zinc
```

**Comment by Dguipla** [comment]
Gracias !! 

Una pregunta en el build.sbt [https://github.com/mjuez/sbt_scala_spark_hello_world/blob/main/build.sbt](url)
¿tenria que incluir también el componente ml (sparkComponents += "ml") ?

**Comment by alvarag** [comment]
Sí, porque es una dependencia que tienes

**Comment by Dguipla** [comment]
Es raro pero estoy intentado entender porque me da este error (Error downloading org.apache.spark:spark-ml_2.12:3.0.1) cuando añado ml (con mllib me genera el .jar)...

**Comment by alvarag** [comment]
¿Te da el problema con tu repositorio o con el que te ponía de ejemplo?

**Comment by Dguipla** [comment]
Al añadir el paquete --> sparkComponents += "ml” no me genera el .jar me da error dice que no lo encuentra…

Si no le pongo este paquete no me da error y me genera el .jar para la clase SelfTraining.  

He estado buscando y no hay mucha información al respecto, pero en todos los casos que he visto solo ponen "mllib" en sparkComponents, no sé si con esta dependencia es suficiente he indirectamente también tiene en cuenta "ml".  De todas maneras, cuando cargo la librería .jar que me genera con solo mllib en DataBricks tampoco me deja hacer un import me sale error. 
Lo hablamos el lunes y os comento mejor.

**Comment by alvarag** [comment]
Para hacer la prueba de si te funciona o no, probar con una instalación local de Spark. Ejecutar el script spark-shell con --jars

```
./spark-shell --jars pathOfjarsWithCommaSeprated
```

**Comment by Dguipla** [comment]
Tenía un problema con la ruta donde se encontraba la clase (es decir que me compilaba una clase vacía, sin nada...)

![image.png](https://images.zenhubusercontent.com/5fe226a8e76f3fd56f6eec06/20977093-cbad-4b62-8a5f-412ab6af72ba)

Ahora me indica que no conoce el $. En DataBricks hacia un import de  sqlContext.implicits._ pero aquí no me funciona.
Por otro lado, en la clase SelfTraining trabajo con otra clase SemiSupervisedDataResults que tendría que estar previamente generada para poder importarla a SelfTraining. 


@alvarag, quizá seria mejor y más rápido hablarlo via Teams. ¿Tendrías algún hueco durante la semana ?

PD: Esta subido en Github.

**Comment by alvarag** [comment]
Si te va bien podríamos quedar mañana por la tarde a las 16:30, por ejemplo.

El import de sqlImplicits debes hacerlo dentro de la clase y no fuera con los otros imports. Es un poco raro el import para que funcione la $-notation, pero deberías ponerlo en el interior de la definición de la clase. En tu caso en la línea 20 por ejemplo.

**Comment by alvarag** [comment]
En cuanto al error que te da por "SemiSupervisedDataResults" es porque dicha clase no la tienes definida. Supongo que estará en otro fichero que no esta subida o esta en otra ruta

**Comment by Dguipla** [comment]
@alvarag Perfecto mañana a las 16:30.  
Por otro lado el error relacionado con "SemiSupervisedDataResults" esta solucionado  era porque no estaba subido el archivo, de lo contrario no consigo eliminar el de sqlImplicits,  he probado con:

import org.apache.spark.sql.SQLImplicits 
import sqlContext.implicits._
import spark.implicits._

y creo que alguno más... todos ellos dentro de la clase pero no consigo que me funcione...

**Comment by alvarag** [comment]
Para poder importar implicits necesitas tener primero una referencia al objeto SparkSession.

En la funcioón/método que necesites utilizar la $-notation debes poner lo siguiente:

```scala
val sql = sparkSession
import sql.implicits._
```

**Comment by alvarag** [comment]
Lo tengo @Dguipla , importa arriba como tenías:

```scala
import org.apache.spark.sql.{SparkSession, SQLContext}
```

Luego abajo donde tenías el val sql... pon:

```scala
val sql = SparkSession.builder().getOrCreate()
```

**Comment by Dguipla** [comment]
Lo acabo de probar y perfecto también lo he probado en Spark y funciona :

![image.png](https://images.zenhubusercontent.com/5fe226a8e76f3fd56f6eec06/ac70ab48-7791-4fec-a1cc-f2a68391e50b)

**Comment by Dguipla** [comment]
@alvarag @jjrodriguez  ya he modificado el nombre de la columna label, para el Self-Training y Co-Training ahora por defecto es "label". 

Por otro lado también he corregido el error con el plugins.sbt . He generado el .jar y funciona clonando el proyecto de Gihub. 

Si lo probais tendria que funcionar, si no me deciis...
